name = "YaoPastaQ"
uuid = "295aef9f-e68b-4375-90fc-eaec2cf620b6"
authors = ["Roger-Luo <rogerluo.rl18@gmail.com> and Chetan Vardhan <chetan.verdhan8@gmail.com>"]
version = "0.1.0"

[deps]
PastaQ = "30b07047-aa8b-4c78-a4e8-24d720215c19"
YaoBase = "a8f54c17-34bc-5a9d-b050-f522fe3f755f"
YaoBlocks = "418bc28f-b43b-5e0b-a6e7-61bbc1a2c1df"

[compat]
PastaQ = "0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12"
YaoBase = "0.14"
YaoBlocks = "0.11"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Yao = "5872b779-8223-5990-8dd0-5abbb0748c8c"

[targets]
test = ["Test", "Yao", "PastaQ"]
